import { ArrowRight, BookOpen, CheckCircle2, Terminal } from 'lucide-react';
import { getCopy } from '../data/editorSchema';
import { SiteContent } from '../data/siteState';
import { SectionLink } from './SectionLink';
import { PharmacyBackground } from './PharmacyBackground';
import { EditableRegion, EditableText } from './VisualEditorContext';

export const Academy = ({ content, copy }: { content: SiteContent['learn']; copy?: Record<string, string> }) => {
  return (
    <EditableRegion elementKey="academy.section" label="Academy section" collection="academy">
      <section id="learn" className="brand-section brand-grid py-28 sm:py-36">
        <PharmacyBackground layout="lab" />
        <div className="brand-glow right-[-14rem] top-20 opacity-50" />
        <div className="relative z-10 mx-auto grid max-w-[1440px] items-center gap-16 px-5 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:px-10">
          <div><div className="mb-6 flex items-center justify-between gap-4 sm:justify-start sm:gap-8"><div className="brand-eyebrow"><BookOpen className="h-3.5 w-3.5" /><EditableText elementKey="academy.eyebrow" copyKey="academy.eyebrow" label="Academy eyebrow">{getCopy(copy, 'academy.eyebrow', 'Code Rx Academy')}</EditableText></div><SectionLink id="learn" /></div><h1 className="brand-title text-5xl sm:text-6xl lg:text-7xl"><EditableText elementKey="academy.title" copyKey="academy.title" label="Academy heading">{getCopy(copy, 'academy.title', 'Learn the stack.')}</EditableText><br /><span className="brand-gradient-text"><EditableText elementKey="academy.title-accent" copyKey="academy.titleAccent" label="Academy heading accent">{getCopy(copy, 'academy.titleAccent', 'Build the bridge.')}</EditableText></span></h1><p className="brand-copy mt-7 max-w-xl text-base sm:text-lg"><EditableText elementKey="academy.description" copyKey="academy.description" label="Academy description">{getCopy(copy, 'academy.description', '')}</EditableText></p>
            <EditableRegion elementKey="academy.benefits" label="Academy benefits" collection="academyBenefits" className="mt-9 space-y-4">{content.benefits.map((item, index) => <div key={`${item}-${index}`} className="flex items-center gap-3 text-sm font-bold text-[#334155]"><CheckCircle2 className="h-5 w-5 text-[#15803d]" /><EditableText elementKey={`academy.benefit.${index}`} copyKey={`learn.benefits.${index}`} label={`Academy benefit ${index + 1}`}>{item}</EditableText></div>)}</EditableRegion>
            <a href="#projects" className="brand-button mt-10"><EditableText elementKey="academy.project-cta" copyKey="academy.projectCta" label="Academy project button">{getCopy(copy, 'academy.projectCta', 'See the project lab')}</EditableText><ArrowRight className="h-4 w-4" /></a>
          </div>
          <EditableRegion elementKey="academy.path-card" label="Learning path card" collection="academySteps" className="brand-card relative overflow-hidden p-5 sm:p-8"><div className="absolute right-0 top-0 h-64 w-64 rounded-full bg-[#b8ff3d]/8 blur-3xl" /><div className="relative mb-7 flex items-center justify-between border-b border-[#16a34a]/20 pb-5"><div className="flex items-center gap-3"><Terminal className="h-4 w-4 text-[#15803d]" /><span className="brand-number"><EditableText elementKey="academy.path-label" copyKey="academy.pathLabel" label="Learning path label">{getCopy(copy, 'academy.pathLabel', 'Learning_path / 08 modules')}</EditableText></span></div><span className="h-2 w-2 rounded-full bg-[#b8ff3d] shadow-[0_0_12px_#b8ff3d]" /></div><div className="relative space-y-2">{content.steps.map((step, index) => <div key={`${step}-${index}`} className="group flex items-center gap-4 rounded-xl border border-transparent px-3 py-3 transition-colors hover:border-[#16a34a]/20 hover:bg-[#b8ff3d]/5 sm:px-4 sm:py-3.5"><span className="brand-number w-8 shrink-0">{String(index + 1).padStart(2, '0')}</span><span className="h-px w-5 bg-[#b8ff3d]/25 transition-all group-hover:w-8 group-hover:bg-[#b8ff3d]" /><span className="text-sm font-bold text-[#334155] transition-colors group-hover:text-[#15803d]"><EditableText elementKey={`academy.step.${index}`} copyKey={`learn.steps.${index}`} label={`Learning module ${index + 1}`}>{step}</EditableText></span></div>)}</div><div className="relative mt-7 flex items-center justify-between border-t border-[#16a34a]/20 pt-5 text-[0.65rem] font-black uppercase tracking-[0.17em] text-[#64748b]"><span><EditableText elementKey="academy.start-anywhere" copyKey="academy.startAnywhere" label="Academy start label">{getCopy(copy, 'academy.startAnywhere', 'Start anywhere')}</EditableText></span><span className="text-[#15803d]"><EditableText elementKey="academy.keep-building" copyKey="academy.keepBuilding" label="Academy keep building label">{getCopy(copy, 'academy.keepBuilding', 'Keep building →')}</EditableText></span></div></EditableRegion>
        </div>
      </section>
    </EditableRegion>
  );
};
