/**
 * CODE Rx SOCIETY — client document delivery service (Phase 8).
 *
 * This module is the only place that decides *what bytes a client may receive*.
 * It never returns a source file: every delivery path renders a stamped
 * representation through `functions/lib/client-delivery(-pdf)`, and every
 * failure becomes a controlled refusal with a client-safe message.
 *
 * The plan is derived from what the document already stores — the
 * `content_snapshot` (rich text blocks or plain text) produced by the Phantom
 * document route, plus any Vault attachment its blocks reference. Nothing new is
 * persisted except the cache key in the existing `storage_reference` column.
 */

import {
  BRAND,
  Canvas,
  DeliveryError,
  decodePng,
  drawPixelText,
  encodePng,
  isPng,
  sha256Hex,
  squareCropArtwork,
  type DecodedImage,
} from './client-delivery';
import {
  buildBrandedPdf,
  stampPdfSource,
  STAMP_DESIGNATION,
  STAMP_HEADLINE,
  STAMP_NOTE,
  type ContentBlock,
  type PresentationCustomization,
} from './client-delivery-pdf';
import { getBrandMark } from './client-delivery-logo';
import { convertOfficeDocument } from './client-delivery-office';

export interface DeliveryMeta {
  projectName: string;
  projectReference: string;
  documentTitle: string;
  documentReference: string;
  version: string;
  clientName: string;
  category: string;
  issuedAt: Date;
  customization?: PresentationCustomization | null;
}

export type DeliverySourceKind =
  | 'rich_text'
  | 'plain_text'
  | 'attachment_pdf'
  | 'attachment_png'
  | 'attachment_text'
  | 'attachment_office'
  | 'unsupported';

export type DeliveryKind = 'generated_pdf' | 'stamped_pdf' | 'stamped_png' | 'converted_pdf';

export interface DeliveryPlan {
  /** True when a stamped client copy can be produced right now. */
  available: boolean;
  kind: DeliveryKind | null;
  sourceKind: DeliverySourceKind;
  /** Short label for the portal and the Phantom panel. */
  label: string;
  contentType: string;
  extension: string;
  /** Client-safe explanation when nothing can be delivered. */
  message: string;
  /** Machine reason for the audit log (never shown to the client). */
  reason: string | null;
}

export interface DeliveryAttachment {
  fileKey: string;
  name: string;
  mimeType: string | null;
  sizeBytes: number | null;
}

export interface DeliveryDocument {
  title: string;
  reference: string;
  version: string;
  category: string;
  contentSnapshot: string | null;
  contentSnapshotFormat: string | null;
}

export interface DeliveryInput {
  meta: DeliveryMeta;
  document: DeliveryDocument;
  attachment: DeliveryAttachment | null;
}

// ---------------------------------------------------------------------------
// Plans
// ---------------------------------------------------------------------------

const OFFICE_MIME_TYPES = [
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/msword',
  'application/vnd.oasis.opendocument.text',
  'application/zip',
];

const TEXT_MIME_TYPES = ['text/plain', 'text/csv', 'text/markdown', 'application/json', 'text/x-markdown'];

export const isOfficeMime = (mimeType: string | null): boolean =>
  !!mimeType && OFFICE_MIME_TYPES.includes(mimeType.toLowerCase());

export const isTextMime = (mimeType: string | null): boolean =>
  !!mimeType && (TEXT_MIME_TYPES.includes(mimeType.toLowerCase()) || mimeType.toLowerCase().startsWith('text/'));

const planFor = (
  kind: DeliveryKind,
  sourceKind: DeliverySourceKind,
  label: string,
  contentType: string,
  extension: string,
): DeliveryPlan => ({
  available: true,
  kind,
  sourceKind,
  label,
  contentType,
  extension,
  message: '',
  reason: null,
});

const refusalFor = (sourceKind: DeliverySourceKind, reason: string, message: string): DeliveryPlan => ({
  available: false,
  kind: null,
  sourceKind,
  label: 'Unavailable',
  contentType: 'application/octet-stream',
  extension: '',
  message,
  reason,
});

const UNSUPPORTED_MESSAGE =
  'A stamped Code Rx copy cannot be produced for this source format, so no download is offered. '
  + 'Contact Code Rx Society for a watermarked copy.';

/**
 * Decides how the document is delivered. Pure: no storage access, so the portal
 * and the Phantom panel can both show the same answer without rendering bytes.
 *
 *   rich text / plain text / text files → a PDF generated by the stamping engine
 *   PDF attachment                      → the PDF repainted with the Code Rx stamp
 *   PNG attachment                      → the PNG repainted with the Code Rx stamp
 *   office document                     → converted to a stamped PDF
 *   anything else                       → refusal (never the original file)
 */
export const planClientDelivery = (input: DeliveryInput): DeliveryPlan => {
  const { document, attachment } = input;

  if (attachment) {
    const mimeType = (attachment.mimeType || '').toLowerCase();
    if (mimeType === 'application/pdf') {
      return planFor('stamped_pdf', 'attachment_pdf', 'Stamped PDF', 'application/pdf', 'pdf');
    }
    if (mimeType === 'image/png') {
      return planFor('stamped_png', 'attachment_png', 'Stamped image', 'image/png', 'png');
    }
    if (isTextMime(mimeType)) {
      return planFor('converted_pdf', 'attachment_text', 'Stamped PDF', 'application/pdf', 'pdf');
    }
    if (isOfficeMime(mimeType)) {
      return planFor('converted_pdf', 'attachment_office', 'Stamped PDF', 'application/pdf', 'pdf');
    }
    return refusalFor('unsupported', 'unsupported_attachment_mime', UNSUPPORTED_MESSAGE);
  }

  const snapshot = document.contentSnapshot || '';
  if (!snapshot.trim()) {
    return refusalFor('unsupported', 'no_source_content',
      'This document has no client-facing content yet. Contact Code Rx Society.');
  }
  const format = (document.contentSnapshotFormat || 'blocks').toLowerCase();
  if (format === 'blocks' || format === 'json' || format === 'html' || format === 'markdown') {
    return planFor('generated_pdf', 'rich_text', 'Stamped PDF', 'application/pdf', 'pdf');
  }
  return planFor('generated_pdf', 'plain_text', 'Stamped PDF', 'application/pdf', 'pdf');
};

// ---------------------------------------------------------------------------
// Snapshot → content blocks
// ---------------------------------------------------------------------------

interface RawBlock {
  type?: string;
  content?: unknown;
  level?: unknown;
  items?: unknown;
  language?: unknown;
  rows?: unknown;
  caption?: unknown;
  fileKey?: unknown;
  attachmentId?: unknown;
  url?: unknown;
}

interface ParsedSnapshot {
  blocks: ContentBlock[];
  /** File references the blocks carry, so the caller can fetch and embed them. */
  attachments: Array<{ fileKey: string; caption: string; type: 'image' | 'file' }>;
  /** True when the only content is a single attachment reference. */
  singleAttachmentOnly: boolean;
}

const asText = (value: unknown): string => {
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) return value.map(asText).filter(Boolean).join(' ');
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    return asText(record.text ?? record.content ?? record.value ?? '');
  }
  return '';
};

const stripHtml = (value: string): string =>
  value
    .replace(/<\s*(script|style)[\s\S]*?<\/\s*\1\s*>/gi, ' ')
    .replace(/<\s*br\s*\/?>/gi, '\n')
    .replace(/<\/\s*(p|div|li|h[1-6]|tr)\s*>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/\n{3,}/g, '\n\n');

const ensureSentence = (value: string): string => value.replace(/^\s+|\s+$/g, '');

/**
 * Markdown-lite → blocks. Enough for the plain-text snapshots the Phantom route
 * can store (`contentText`) and for text files delivered as stamped PDFs.
 */
export const textToBlocks = (value: string): ContentBlock[] => {
  const blocks: ContentBlock[] = [];
  const lines = value.replace(/\r\n?/g, '\n').split('\n');
  let paragraph: string[] = [];
  let list: { items: string[]; ordered: boolean } | null = null;
  let code: { lines: string[]; language?: string } | null = null;
  let quote: string[] = [];

  const flushParagraph = () => {
    const text = ensureSentence(paragraph.join(' '));
    if (text) blocks.push({ type: 'paragraph', text });
    paragraph = [];
  };
  const flushList = () => {
    if (list && list.items.length) blocks.push({ type: 'list', items: list.items, ordered: list.ordered });
    list = null;
  };
  const flushQuote = () => {
    const text = ensureSentence(quote.join(' '));
    if (text) blocks.push({ type: 'quote', text });
    quote = [];
  };
  const flushAll = () => { flushParagraph(); flushList(); flushQuote(); };

  for (const rawLine of lines) {
    const line = rawLine.replace(/\s+$/, '');
    const fence = /^\s*```(\w*)\s*$/.exec(line);
    if (fence) {
      if (code) {
        blocks.push({ type: 'code', text: code.lines.join('\n'), language: code.language });
        code = null;
      } else {
        flushAll();
        code = { lines: [], language: fence[1] || undefined };
      }
      continue;
    }
    if (code) {
      code.lines.push(rawLine);
      continue;
    }
    if (!line.trim()) {
      flushAll();
      continue;
    }
    const heading = /^(#{1,4})\s+(.*)$/.exec(line);
    if (heading) {
      flushAll();
      blocks.push({ type: 'heading', text: heading[2], level: heading[1].length });
      continue;
    }
    if (/^\s*([-*_])\s*\1\s*\1[\s\-*_]*$/.test(line.replace(/\s/g, '')) || /^-{3,}$/.test(line.trim())) {
      flushAll();
      blocks.push({ type: 'divider' });
      continue;
    }
    const bullet = /^\s*[-*+]\s+(.*)$/.exec(line);
    const numbered = /^\s*\d+[.)]\s+(.*)$/.exec(line);
    if (bullet || numbered) {
      flushParagraph();
      flushQuote();
      const ordered = !!numbered;
      if (!list || list.ordered !== ordered) {
        flushList();
        list = { items: [], ordered };
      }
      list.items.push((bullet ? bullet[1] : numbered![1]).replace(/\*\*(.*?)\*\*/g, '$1'));
      continue;
    }
    if (/^\s*>\s?/.test(line)) {
      flushParagraph();
      flushList();
      quote.push(line.replace(/^\s*>\s?/, ''));
      continue;
    }
    paragraph.push(line.replace(/\*\*(.*?)\*\*/g, '$1'));
  }
  if (code) blocks.push({ type: 'code', text: code.lines.join('\n'), language: code.language });
  flushAll();
  return blocks;
};

/**
 * Normalises whatever the snapshot holds into the renderer's block model.
 * Rich text is stored as the Vault block list, so the mapping keeps headings,
 * lists, tables, callouts and code — the structure of a Code Rx document.
 */
export const parseSnapshot = (snapshot: string, format: string | null): ParsedSnapshot => {
  const attachments: ParsedSnapshot['attachments'] = [];
  const normalized = (format || 'blocks').toLowerCase();
  let raw: unknown = null;
  if (normalized === 'blocks' || normalized === 'json') {
    try {
      raw = JSON.parse(snapshot);
    } catch {
      raw = null;
    }
  }

  if (raw && typeof raw === 'object' && !Array.isArray(raw) && Array.isArray((raw as { blocks?: unknown }).blocks)) {
    raw = (raw as { blocks: unknown[] }).blocks;
  }

  const blocks: ContentBlock[] = [];
  if (Array.isArray(raw)) {
    for (const entry of raw as RawBlock[]) {
      const type = String(entry?.type || 'paragraph');
      const content = asText(entry?.content);
      switch (type) {
        case 'heading':
          blocks.push({ type: 'heading', text: content, level: Math.max(1, Math.min(4, Number(entry?.level) || 1)) });
          break;
        case 'paragraph':
          if (content.trim()) blocks.push({ type: 'paragraph', text: content });
          break;
        case 'bulletList':
        case 'numberedList': {
          const items = Array.isArray(entry?.items) ? (entry!.items as unknown[]).map(asText).filter(Boolean) : [];
          if (items.length) blocks.push({ type: 'list', items, ordered: type === 'numberedList' });
          break;
        }
        case 'checklist': {
          const items = Array.isArray(entry?.items)
            ? (entry!.items as unknown[]).map((item) => {
              const record = (item || {}) as Record<string, unknown>;
              return `${record.checked || record.done ? '[x]' : '[ ]'} ${asText(record.text ?? record.label ?? item)}`.trim();
            }).filter((item) => item.length > 3)
            : [];
          if (items.length) blocks.push({ type: 'list', items, ordered: false });
          break;
        }
        case 'quote':
          if (content.trim()) blocks.push({ type: 'quote', text: content });
          break;
        case 'callout':
          if (content.trim()) blocks.push({ type: 'callout', text: content, variant: String((entry as { variant?: unknown })?.variant || '') });
          break;
        case 'code':
          blocks.push({ type: 'code', text: content || String((entry as { code?: unknown })?.code || ''), language: String(entry?.language || '') });
          break;
        case 'divider':
          blocks.push({ type: 'divider' });
          break;
        case 'table': {
          const rows = Array.isArray(entry?.rows)
            ? (entry!.rows as unknown[]).map((row) => (Array.isArray(row) ? row.map(asText) : [asText(row)]))
            : [];
          if (rows.length) blocks.push({ type: 'table', rows });
          break;
        }
        case 'image':
        case 'file':
        case 'embed': {
          const fileKey = typeof entry?.fileKey === 'string' ? entry.fileKey : '';
          const caption = asText(entry?.caption) || asText(entry?.content) || (type === 'image' ? 'Figure' : 'Attachment');
          if (fileKey) {
            attachments.push({ fileKey, caption, type: type === 'image' ? 'image' : 'file' });
            blocks.push(type === 'image'
              ? { type: 'image', caption }
              : { type: 'file', caption });
          } else if (content.trim()) {
            blocks.push({ type: 'paragraph', text: content });
          }
          break;
        }
        case 'formula':
          if (content.trim()) blocks.push({ type: 'code', text: content });
          break;
        default:
          if (content.trim()) blocks.push({ type: 'paragraph', text: content });
          break;
      }
    }
  }

  if (!blocks.length) {
    const source = normalized === 'html' ? stripHtml(snapshot) : snapshot;
    blocks.push(...textToBlocks(source));
  }

  const textual = blocks.filter((block) => block.type !== 'image' && block.type !== 'file');
  const singleAttachmentOnly = textual.length === 0 && attachments.length === 1;

  return { blocks, attachments, singleAttachmentOnly };
};

// ---------------------------------------------------------------------------
// Stamped raster delivery (PNG sources)
// ---------------------------------------------------------------------------

export interface StampedImageOptions {
  meta: DeliveryMeta;
  image: DecodedImage;
  logo?: DecodedImage | null;
  /** Marks a page break for multi-page raster deliveries (unused at present). */
  page?: number;
  pageCount?: number;
}

/**
 * Repaints a raster source as a branded Code Rx page: header band with the mark,
 * the client-document designation, the metadata block, the artwork itself with a
 * diagonal watermark burned into the pixels, and the footer. The result is a new
 * PNG — the source pixels never leave the pipeline unmarked.
 */
export const buildStampedImage = async (options: StampedImageOptions): Promise<Uint8Array> => {
  const { meta, image, logo } = options;
  const scale = image.width >= 900 ? 3 : image.width >= 480 ? 2 : 1;
  const pad = 18 * scale;
  const gap = 10 * scale;
  const headerHeight = 78 * scale;
  const footerHeight = 62 * scale;

  const contentWidth = Math.max(image.width, 520 * scale);
  const width = contentWidth + pad * 2;
  const rows: Array<[string, string]> = [
    ['PROJECT', meta.projectName],
    ['DOCUMENT', meta.documentTitle],
    ['REFERENCE', meta.documentReference],
    ['VERSION', meta.version],
    ['CLIENT', meta.clientName],
    ['DESIGNATION', STAMP_DESIGNATION],
  ];
  const rowHeight = 20 * scale;
  const metaBlockHeight = rows.length * rowHeight + 12 * scale;

  const imageScale = Math.min(1, (width - pad * 2) / image.width);
  const drawWidth = Math.max(1, Math.round(image.width * imageScale));
  const drawHeight = Math.max(1, Math.round(image.height * imageScale));
  const height = headerHeight + gap + metaBlockHeight + gap + drawHeight + gap + footerHeight;

  const canvas = new Canvas(width, height);
  canvas.fillRect(0, 0, width, height, BRAND.white, 1);

  // --- header band ---------------------------------------------------------
  canvas.fillRect(0, 0, width, headerHeight, BRAND.greenDark, 1);
  canvas.fillRect(0, headerHeight - 3 * scale, width, 3 * scale, BRAND.green, 1);
  const markSize = 46 * scale;
  if (logo) {
    const markCanvas = Canvas.from(logo);
    canvas.drawImage(markCanvas, pad, (headerHeight - markSize) / 2, markSize / logo.width, 1);
  }
  const titleText = STAMP_HEADLINE.toUpperCase();
  const titleScale = Math.max(2, Math.min(6, Math.floor(((width - pad * 2 - markSize - gap) / (titleText.length * 6)) * 1)));
  const textX = pad + (logo ? markSize + gap : 0);
  drawPixelText(canvas, titleText, textX, Math.round(headerHeight * 0.26), titleScale, BRAND.white, 1);
  const subScale = Math.max(1, Math.floor(titleScale / 2));
  drawPixelText(canvas, STAMP_DESIGNATION, textX, Math.round(headerHeight * 0.26) + 8 * titleScale + 4, subScale, [214, 232, 224], 1);
  const issuedText = `ISSUED ${meta.issuedAt.toISOString().slice(0, 10)}`;
  const issuedWidth = issuedText.length * 6 * subScale;
  drawPixelText(canvas, issuedText, Math.max(pad, width - pad - issuedWidth), Math.round(headerHeight * 0.26), subScale, [214, 232, 224], 1);

  // --- metadata block ------------------------------------------------------
  let cursorY = headerHeight + gap;
  canvas.fillRect(pad, cursorY, width - pad * 2, metaBlockHeight, [239, 247, 243], 1);
  canvas.strokeRect(pad, cursorY, width - pad * 2, metaBlockHeight, [216, 232, 224], Math.max(1, scale), 1);
  let rowY = cursorY + 10 * scale;
  const labelScale = Math.max(1, scale);
  const valueScale = Math.max(1, scale + 1);
  const labelWidth = 22 * (5 + 1) * labelScale;
  for (const [label, value] of rows) {
    drawPixelText(canvas, label, pad + 8 * scale, rowY, labelScale, BRAND.slate, 1);
    drawPixelText(canvas, value.slice(0, Math.floor((width - pad * 2 - labelWidth - 24 * scale) / (6 * valueScale))),
      pad + 8 * scale + labelWidth, rowY, valueScale, BRAND.ink, 1);
    rowY += rowHeight;
  }
  cursorY += metaBlockHeight + gap;

  // --- artwork with the watermark burned in --------------------------------
  const artwork = new Canvas(drawWidth, drawHeight);
  artwork.drawImage(Canvas.from(image), 0, 0, 1, 1);
  const watermarkScale = Math.max(2, Math.floor(Math.min(drawWidth / 26, drawHeight / 9) / 6));
  const artCenterX = drawWidth / 2;
  const artCenterY = drawHeight / 2;
  // The rotated wordmark stays low-left; the full logo sits top-right of
  // centre, so the two never overlap.
  const textAnchorX = artCenterX - drawWidth * 0.17;
  const textAnchorY = artCenterY + drawHeight * 0.11;
  artwork.drawRotatedText('CODE RX SOCIETY', textAnchorX, textAnchorY, watermarkScale, -Math.atan2(1, 2.6), [12, 32, 24], 0.10);
  artwork.drawRotatedText(STAMP_DESIGNATION, textAnchorX, textAnchorY + (8 + 3) * watermarkScale, Math.max(1, Math.floor(watermarkScale / 3)), -Math.atan2(1, 2.6), [12, 32, 24], 0.08);
  if (logo) {
    // One full, square logo — no source padding — at the documented 10% opacity.
    const cropped = squareCropArtwork(logo);
    const markSize = Math.max(24, Math.round(Math.min(drawWidth, drawHeight) * 0.38));
    const markCenterX = drawWidth * 0.66;
    const markCenterY = drawHeight * 0.32;
    artwork.drawImage(
      Canvas.from(cropped),
      Math.round(markCenterX - markSize / 2),
      Math.round(markCenterY - markSize / 2),
      markSize / cropped.width,
      0.10,
    );
  }
  canvas.drawImage(artwork, pad, cursorY, 1, 1);
  canvas.strokeRect(pad, cursorY, drawWidth, drawHeight, [216, 232, 224], Math.max(1, scale), 1);
  cursorY += drawHeight + gap;

  // --- footer --------------------------------------------------------------
  canvas.fillRect(0, height - footerHeight, width, footerHeight, BRAND.greenDark, 1);
  canvas.fillRect(0, height - footerHeight, width, 2 * scale, BRAND.green, 1);
  const footerScale = Math.max(1, scale);
  const footerTop = height - footerHeight + 12 * scale;
  const leftFooter = `${STAMP_HEADLINE.toUpperCase()}  ·  ${STAMP_DESIGNATION}`;
  drawPixelText(canvas, leftFooter, pad, footerTop, footerScale, BRAND.white, 1);
  const pageLabel = options.pageCount && options.pageCount > 1
    ? `PAGE ${options.page ?? 1} OF ${options.pageCount}`
    : 'CLIENT COPY';
  const pageWidth = pageLabel.length * 6 * footerScale;
  drawPixelText(canvas, pageLabel, Math.max(pad, width - pad - pageWidth), footerTop, footerScale, BRAND.white, 1);
  const detail = `${meta.clientName.toUpperCase()}  ·  ${meta.projectName.toUpperCase()}`
    + `  ·  ${meta.projectReference.toUpperCase()}  ·  ${meta.documentReference.toUpperCase()}  ·  V${meta.version}`;
  drawPixelText(canvas, detail.slice(0, Math.floor((width - pad * 2) / (6 * footerScale))),
    pad, footerTop + 8 * footerScale + 4, footerScale, [198, 222, 212], 1);
  drawPixelText(canvas, STAMP_NOTE.toUpperCase(), pad, footerTop + 16 * footerScale + 6, footerScale, [178, 206, 194], 1);

  return encodePng({ width, height, rgba: canvas.rgba });
};

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

export interface RenderedDelivery {
  bytes: Uint8Array;
  contentType: string;
  extension: string;
  kind: DeliveryKind;
  /** sha256 of the delivered bytes — recorded in the audit log. */
  sha256: string;
  /** sha256 of the source material the artifact was rendered from. */
  sourceFingerprint: string;
}

export class DeliveryRefusal extends Error {
  readonly reason: string;
  readonly plan: DeliveryPlan;
  constructor(reason: string, message: string, plan: DeliveryPlan) {
    super(message);
    this.name = 'DeliveryRefusal';
    this.reason = reason;
    this.plan = plan;
  }
}

export interface RenderInput extends DeliveryInput {
  /** Raw bytes of the primary attachment, when the plan needs them. */
  attachmentBytes?: Uint8Array | null;
  /** Bytes of the images the rich-text blocks reference, keyed by fileKey. */
  embeddedImages?: Record<string, Uint8Array | null>;
}

export const sourceFingerprint = async (input: RenderInput): Promise<string> => {
  const parts = [
    input.document.reference,
    input.document.version,
    input.document.contentSnapshot || '',
    input.attachment?.fileKey || '',
    String(input.attachment?.sizeBytes ?? ''),
    JSON.stringify(input.meta?.customization || {}),
  ];
  return (await sha256Hex(parts.join('\u0000'))).slice(0, 16);
};

const metaFor = (meta: DeliveryMeta) => ({
  projectName: meta.projectName,
  projectReference: meta.projectReference,
  documentTitle: meta.documentTitle,
  documentReference: meta.documentReference,
  version: meta.version,
  clientName: meta.clientName,
  category: meta.category,
  issuedAt: meta.issuedAt,
  customization: meta.customization || null,
});

/**
 * Renders the stamped client copy. Every branch either produces a stamped
 * artifact or throws `DeliveryRefusal`; none of them returns source bytes.
 */
export const renderClientDelivery = async (input: RenderInput): Promise<RenderedDelivery> => {
  const plan = planClientDelivery(input);
  if (!plan.available || !plan.kind) {
    throw new DeliveryRefusal(plan.reason || 'delivery_unavailable', plan.message, plan);
  }
  const logo = await getBrandMark();
  const fingerprint = await sourceFingerprint(input);
  const attempt = async (): Promise<Uint8Array> => {
    if (input.meta?.customization?.rawDocumentDelivery) {
      if (input.attachmentBytes && input.attachmentBytes.length) {
        return input.attachmentBytes;
      }
    }
    switch (plan.sourceKind) {
      case 'attachment_pdf': {
        const bytes = input.attachmentBytes;
        if (!bytes || !bytes.length) throw new DeliveryRefusal('attachment_unavailable', plan.message, plan);
        const result = await stampPdfSource(bytes, metaFor(input.meta), logo);
        if (!result.ok) {
          throw new DeliveryRefusal(result.error.reason, UNSUPPORTED_MESSAGE, plan);
        }
        return result.bytes;
      }
      case 'attachment_png': {
        const bytes = input.attachmentBytes;
        if (!bytes || !bytes.length) throw new DeliveryRefusal('attachment_unavailable', plan.message, plan);
        if (!isPng(bytes)) throw new DeliveryRefusal('not_png', UNSUPPORTED_MESSAGE, plan);
        const image = await decodePng(bytes);
        return buildStampedImage({ meta: input.meta, image, logo });
      }
      case 'attachment_office': {
        const bytes = input.attachmentBytes;
        if (!bytes || !bytes.length) throw new DeliveryRefusal('attachment_unavailable', plan.message, plan);
        const converted = await convertOfficeDocument(bytes, input.attachment?.mimeType || null);
        if (!converted) throw new DeliveryRefusal('office_conversion_unsupported', UNSUPPORTED_MESSAGE, plan);
        const blocks = [...textToBlocks(converted.text)];
        if (converted.notes.length) {
          blocks.push({ type: 'divider' });
          blocks.push({ type: 'list', items: converted.notes, ordered: false });
        }
        return buildBrandedPdf({ meta: metaFor(input.meta), blocks, logo });
      }
      case 'attachment_text': {
        const bytes = input.attachmentBytes;
        if (!bytes || !bytes.length) throw new DeliveryRefusal('attachment_unavailable', plan.message, plan);
        const text = new TextDecoder('utf-8', { fatal: false }).decode(bytes);
        const blocks = textToBlocks(text);
        return buildBrandedPdf({ meta: metaFor(input.meta), blocks, logo });
      }
      default: {
        const parsed = parseSnapshot(input.document.contentSnapshot || '', input.document.contentSnapshotFormat);
        const blocks = await attachImages(parsed.blocks, parsed.attachments, input.embeddedImages || {});
        return buildBrandedPdf({ meta: metaFor(input.meta), blocks, logo });
      }
    }
  };

  let bytes: Uint8Array;
  try {
    bytes = await attempt();
  } catch (error) {
    if (error instanceof DeliveryRefusal) throw error;
    const reason = error instanceof DeliveryError ? error.reason : 'delivery_render_failed';
    // Fail closed: a renderer problem must never degrade into a passthrough.
    throw new DeliveryRefusal(reason, UNSUPPORTED_MESSAGE, plan);
  }
  if (!bytes.length) throw new DeliveryRefusal('empty_artifact', UNSUPPORTED_MESSAGE, plan);

  return {
    bytes,
    contentType: plan.contentType,
    extension: plan.extension,
    kind: plan.kind,
    sha256: await sha256Hex(bytes),
    sourceFingerprint: fingerprint,
  };
};

/** Decodes and embeds the images a rich-text document references. */
const attachImages = async (
  blocks: ContentBlock[],
  attachments: ParsedSnapshot['attachments'],
  embedded: Record<string, Uint8Array | null>,
): Promise<ContentBlock[]> => {
  const decoded = new Map<string, DecodedImage>();
  for (const attachment of attachments) {
    if (attachment.type !== 'image') continue;
    const bytes = embedded[attachment.fileKey];
    if (!bytes || !isPng(bytes)) continue;
    try {
      decoded.set(attachment.fileKey, await decodePng(bytes));
    } catch {
      // An image the engine cannot decode is omitted with a note — the source
      // bytes are never bundled into the artifact.
    }
  }
  let index = 0;
  return blocks.map((block) => {
    if (block.type === 'image') {
      const attachment = attachments[index];
      index += 1;
      const image = attachment ? decoded.get(attachment.fileKey) : undefined;
      return { type: 'image', caption: block.caption, image: image || null };
    }
    return block;
  });
};

// ---------------------------------------------------------------------------
// Artifact cache (R2, under the client-exports/ prefix only)
// ---------------------------------------------------------------------------

export const CLIENT_ARTIFACT_PREFIX = 'client-exports/';

export const artifactKey = (
  clientPublicId: string,
  documentPublicId: string,
  extension: string,
  fingerprint: string,
): string =>
  `${CLIENT_ARTIFACT_PREFIX}${clientPublicId}/${documentPublicId}/crx-stamped-${fingerprint}.${extension}`;

export const safeSegment = (value: string): string =>
  value.replace(/[^A-Za-z0-9._-]/g, '_').slice(0, 64) || 'unknown';

export interface ArtifactResult {
  key: string;
  contentType: string;
  size: number;
  sha256: string;
  kind: DeliveryKind;
  filename: string;
  cached: boolean;
}

export const deliveryFilename = (meta: DeliveryMeta, extension: string): string =>
  `CODE-Rx-${safeSegment(meta.documentReference)}-v${safeSegment(meta.version)}-client-copy.${extension}`;

export interface BucketLike {
  get(key: string): Promise<{ arrayBuffer(): Promise<ArrayBuffer> } | null>;
  put(key: string, value: Uint8Array, options?: { httpMetadata?: { contentType?: string } }): Promise<unknown>;
}

/**
 * Returns the stamped artifact for the document, rendering and caching it when
 * the cached copy is missing or stale. The cache key carries a fingerprint of
 * the source, so a changed source or version always produces a new artifact and
 * a stale one can never be served.
 */
export const ensureClientDeliveryArtifact = async (options: {
  bucket: BucketLike;
  clientPublicId: string;
  documentPublicId: string;
  input: RenderInput;
}): Promise<ArtifactResult> => {
  const { bucket, clientPublicId, documentPublicId, input } = options;
  const plan = planClientDelivery(input);
  if (!plan.available || !plan.kind) {
    throw new DeliveryRefusal(plan.reason || 'delivery_unavailable', plan.message, plan);
  }
  const fingerprint = await sourceFingerprint(input);
  const key = artifactKey(clientPublicId, documentPublicId, plan.extension, fingerprint);
  const filename = deliveryFilename(input.meta, plan.extension);

  const cached = await bucket.get(key);
  if (cached) {
    const bytes = new Uint8Array(await cached.arrayBuffer());
    if (bytes.length) {
      return {
        key,
        contentType: plan.contentType,
        size: bytes.length,
        sha256: await sha256Hex(bytes),
        kind: plan.kind,
        filename,
        cached: true,
      };
    }
  }

  const rendered = await renderClientDelivery(input);
  await bucket.put(key, rendered.bytes, { httpMetadata: { contentType: rendered.contentType } });
  return {
    key,
    contentType: rendered.contentType,
    size: rendered.bytes.length,
    sha256: rendered.sha256,
    kind: rendered.kind,
    filename,
    cached: false,
  };
};

/**
 * Re-renders and replaces the cached artifact, ignoring any cached copy. Used by
 * the Phantom "prepare client copy" action, which deliberately regenerates.
 */
export const refreshClientDeliveryArtifact = async (options: {
  bucket: BucketLike;
  clientPublicId: string;
  documentPublicId: string;
  input: RenderInput;
}): Promise<ArtifactResult> => {
  const { bucket, clientPublicId, documentPublicId, input } = options;
  const plan = planClientDelivery(input);
  if (!plan.available || !plan.kind) {
    throw new DeliveryRefusal(plan.reason || 'delivery_unavailable', plan.message, plan);
  }
  const fingerprint = await sourceFingerprint(input);
  const key = artifactKey(clientPublicId, documentPublicId, plan.extension, fingerprint);
  const rendered = await renderClientDelivery(input);
  await bucket.put(key, rendered.bytes, { httpMetadata: { contentType: rendered.contentType } });
  return {
    key,
    contentType: rendered.contentType,
    size: rendered.bytes.length,
    sha256: rendered.sha256,
    kind: rendered.kind,
    filename: deliveryFilename(input.meta, plan.extension),
    cached: false,
  };
};

/**
 * Loads the bytes of an artifact the pipeline generated. A key that is not one
 * of ours (a legacy hand-placed file, an internal `vault/...` object) is never
 * served: the caller regenerates instead.
 */
export const readClientArtifact = async (
  bucket: BucketLike,
  key: string | null,
): Promise<Uint8Array | null> => {
  if (!key || !key.startsWith(CLIENT_ARTIFACT_PREFIX)) return null;
  const object = await bucket.get(key);
  if (!object) return null;
  const bytes = new Uint8Array(await object.arrayBuffer());
  return bytes.length ? bytes : null;
};

export const isDeliveryArtifactKey = (key: string | null | undefined, clientPublicId: string, documentPublicId: string): boolean =>
  !!key && key.startsWith(`${CLIENT_ARTIFACT_PREFIX}${clientPublicId}/${documentPublicId}/crx-stamped-`);
